# ТЗ

Сравнить контрольные точки Эталонного реестра мероприятий и ГИИС "Электронный бюджет" (950 в сравнении с тем что ему соответствует в УНП ЭБ (там где-то около 532))

Надо сделать таблицу: ID/мероприятие/Кол-во КТ в Эталонном реестре/Кол-во КТ в Электронном бюджете

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Загрузка файла каталога 4852

df_4852 = pd.read_csv('4852_new\export_Подкаталог_-4852_родитель-400_08_10_2021_11_30_03.csv', delimiter = ';'\
                      , encoding = 'ANSI', parse_dates = True, header=1)
df_4852.head(3)

,global_id,system_object_id,global_object_id,system_global_object_id,Наименование КТ,Плановая дата КТ,Фактическая дата КТ,Статус,Состояние подписи,Статус объекта
0,2516,NaN,201594,8216403250,Проведено установочное совещание с организацие...,18.03.2021,18.03.2021,Подготовка,Подписано технологической подписью,активна
1,2517,NaN,201594,8216403250,Проведен текущий мониторинг внедрения программ...,30.06.2021,NaN,Подготовка,Подписано технологической подписью,активна
2,2518,NaN,201594,8216403250,Проведено информационно-аналитическое исследов...,01.08.2021,NaN,Подготовка,Подписано технологической подписью,активна

In [3]:
#Количество записей в соединенных выгрузках
len(df_4852)

8200

In [4]:
#Удаление дубликатов по столбцам 'Наименование КТ', 'Плановая дата КТ', 'Фактическая дата КТ'
#df_4852.drop_duplicates(subset = ['Наименование КТ', 'Плановая дата КТ', 'Фактическая дата КТ'], keep='last', inplace = True)

In [5]:
#Количество записей в очищенной от дубликатов выгрузке
#len(df_4852)

In [6]:
df_4852.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8200 entries, 0 to 8199
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   global_id                8200 non-null   int64
 1   system_object_id         927 non-null    float64
 2   global_object_id         8200 non-null   int64
 3   system_global_object_id  5292 non-null   object
 4   Наименование КТ          8200 non-null   object
 5   Плановая дата КТ         8200 non-null   object
 6   Фактическая дата КТ      1665 non-null   object
 7   Статус                   6968 non-null   object
 8   Состояние подписи        8200 non-null   object
 9   Статус объекта           8200 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 640.8+ KB

In [7]:
df_4852['Плановая дата КТ'] = df_4852['Плановая дата КТ'].astype('datetime64')

In [8]:
#Добавление столбца год
df_4852['Год_КТ'] = df_4852['Плановая дата КТ'].dt.year

In [9]:
#Количество КТ по годам
df_4852['Год_КТ'].value_counts()

2021    5850
2022     818
2023     746
2024     620
2020      71
2019      38
2025      22
2027       9
2029       8
2026       6
2028       6
2030       6
Name: Год_КТ, dtype: int64

In [10]:
#Сохранение таблицы только с 2021 годом
df_4852_2021 = df_4852[df_4852['Год_КТ'] == 2021].copy()

In [11]:
#Загрузка ЭР (облегченная версия)
er = pd.read_excel('er_lite_1.xlsx')

In [12]:
er.head(3)

,global_id,system_object_id,Наименование мероприятия (результата),Тип мероприятия (результата),Тип мероприятия (результата) (временно),Национальная цель,Показатель достижения цели,Национальный проект,Государственная программа,Федеральный проект,...,Структурный элемент (результат ФП или мероприятие ГП),Фактор,Подфактор,Комплекс мероприятий,Организация,Должность,ФИО,Наименование показателя мероприятия (результата),Ед. измерения,Ед. измерения (временно)
0,201471,8498468734,На базе образовательных организаций высшего об...,Меры господдержки (в т.ч. субсидии юридическим...,NaN,Возможности для самореализации и развития тала...,Вхождение РФ в число 10-ти ведущих стран мира ...,Образование,Развитие образования,Современная школа,...,Результат ФП,2.1.3 Кадровое обеспечение системы общего обра...,NaN,Обеспечение условий для профессионального разв...,Министерство просвещения Российской Федерации,Директор Департамента,Милехин Андрей Викторович,Количество созданных педагогических технопарк...,Единица,Единица
1,201472,8498454666,Педагогические работники и управленческие кадр...,Привлечение квалифицированных кадров,NaN,Возможности для самореализации и развития тала...,Вхождение РФ в число 10-ти ведущих стран мира ...,Образование,Развитие образования,Современная школа,...,Результат ФП,2.1.3 Кадровое обеспечение системы общего обра...,NaN,Обеспечение условий для профессионального разв...,Министерство просвещения Российской Федерации,Директор Департамента,Милехин Андрей Викторович,Доля педагогических работников и управленчески...,Процент,Процент
2,201485,8497485987,На базе общеобразовательных организаций создан...,"Приобретение товаров, работ, услуг","Приобретение товаров, работ, услуг",Возможности для самореализации и развития тала...,"Формирование эффективной системы выявления, по...",Образование,Развитие образования,Современная школа,...,Результат ФП,2.2.1 Повышение доступности дополнительного об...,NaN,"Создание новых мест, в том числе путем развити...",Министерство просвещения Российской Федерации,Директор Департамента,Руденок Мария Алексеевна,Количество созданных и функционирующирх на баз...,Единица,Единица

In [13]:
#Кол-во id в ЭР
er['global_id'].count()

950

In [14]:
#Кол-во уникальных id в ЭР
er['global_id'].nunique()

950

In [15]:
er.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 25 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   global_id                                                               950 non-null    int64
 1   system_object_id                                                        655 non-null    object
 2   Наименование мероприятия (результата)                                   950 non-null    object
 3   Тип мероприятия (результата)                                            950 non-null    object
 4   Тип мероприятия (результата) (временно)                                 676 non-null    object
 5   Национальная цель                                                       950 non-null    object
 6   Показатель достижения цели                                              950 non-null    object
 7   Национальный проект                                                     550 non-null    object
 8   Государственная программа                                               740 non-null    object
 9   Федеральный проект                                                      513 non-null    object
 10  Основное мероприятие ГП                                                 246 non-null    object
 11  Заместители Председателя Правительства                                  932 non-null    object
 12  Документ-основание для реализации (реквизиты) (если не ГП и НП)         251 non-null    object
 13  Характеристика результата (ожидаемый результат реализации мероприятия)  950 non-null    object
 14  Код из Электронного бюджета                                             494 non-null    object
 15  Структурный элемент (результат ФП или мероприятие ГП)                   784 non-null    object
 16  Фактор                                                                  950 non-null    object
 17  Подфактор                                                               457 non-null    object
 18  Комплекс мероприятий                                                    950 non-null    object
 19  Организация                                                             950 non-null    object
 20  Должность                                                               950 non-null    object
 21  ФИО                                                                     950 non-null    object
 22  Наименование показателя мероприятия (результата)                        950 non-null    object
 23  Ед. измерения                                                           950 non-null    object
 24  Ед. измерения (временно)                                                648 non-null    object
dtypes: int64(1), object(24)
memory usage: 185.7+ KB

In [16]:
#Количество мероприятий ЭР являющихся результатами ФП
er['Федеральный проект'].notna()\
    .sum()

513

In [17]:
#Отдельная таблица с мероприятиями, входящими в ФП
er_fp = er[er['Федеральный проект'].notna()].copy()

In [18]:
er_fp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 513 entries, 0 to 949
Data columns (total 25 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   global_id                                                               513 non-null    int64
 1   system_object_id                                                        463 non-null    object
 2   Наименование мероприятия (результата)                                   513 non-null    object
 3   Тип мероприятия (результата)                                            513 non-null    object
 4   Тип мероприятия (результата) (временно)                                 436 non-null    object
 5   Национальная цель                                                       513 non-null    object
 6   Показатель достижения цели                                              513 non-null    object
 7   Национальный проект                                                     513 non-null    object
 8   Государственная программа                                               472 non-null    object
 9   Федеральный проект                                                      513 non-null    object
 10  Основное мероприятие ГП                                                 0 non-null      object
 11  Заместители Председателя Правительства                                  503 non-null    object
 12  Документ-основание для реализации (реквизиты) (если не ГП и НП)         51 non-null     object
 13  Характеристика результата (ожидаемый результат реализации мероприятия)  513 non-null    object
 14  Код из Электронного бюджета                                             481 non-null    object
 15  Структурный элемент (результат ФП или мероприятие ГП)                   509 non-null    object
 16  Фактор                                                                  513 non-null    object
 17  Подфактор                                                               210 non-null    object
 18  Комплекс мероприятий                                                    513 non-null    object
 19  Организация                                                             513 non-null    object
 20  Должность                                                               513 non-null    object
 21  ФИО                                                                     513 non-null    object
 22  Наименование показателя мероприятия (результата)                        513 non-null    object
 23  Ед. измерения                                                           513 non-null    object
 24  Ед. измерения (временно)                                                455 non-null    object
dtypes: int64(1), object(24)
memory usage: 104.2+ KB

In [19]:
df_4852.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8200 entries, 0 to 8199
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   global_id                8200 non-null   int64
 1   system_object_id         927 non-null    float64
 2   global_object_id         8200 non-null   int64
 3   system_global_object_id  5292 non-null   object
 4   Наименование КТ          8200 non-null   object
 5   Плановая дата КТ         8200 non-null   datetime64[ns]
 6   Фактическая дата КТ      1665 non-null   object
 7   Статус                   6968 non-null   object
 8   Состояние подписи        8200 non-null   object
 9   Статус объекта           8200 non-null   object
 10  Год_КТ                   8200 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 704.8+ KB

In [20]:
#df_4852_1 = df_4852.astype({'global_id': 'object'}).dtypes

In [21]:
df_4852_2021.head(3)

,global_id,system_object_id,global_object_id,system_global_object_id,Наименование КТ,Плановая дата КТ,Фактическая дата КТ,Статус,Состояние подписи,Статус объекта,Год_КТ
0,2516,NaN,201594,8216403250,Проведено установочное совещание с организацие...,2021-03-18,18.03.2021,Подготовка,Подписано технологической подписью,активна,2021
1,2517,NaN,201594,8216403250,Проведен текущий мониторинг внедрения программ...,2021-06-30,NaN,Подготовка,Подписано технологической подписью,активна,2021
2,2518,NaN,201594,8216403250,Проведено информационно-аналитическое исследов...,2021-01-08,NaN,Подготовка,Подписано технологической подписью,активна,2021

In [22]:
#Проверка на дубли в наименованиях КТ в одном мероприятии
test_df = df_4852_2021.groupby('global_object_id')[['Наименование КТ', 'Плановая дата КТ']].count()
test_df[test_df['Наименование КТ'] != test_df['Плановая дата КТ']]

Empty DataFrame
Columns: [Наименование КТ, Плановая дата КТ]
Index: []

Дублей не выявлено

In [23]:
#Сводная таблица
ct_4852_count = df_4852_2021.groupby('global_object_id')['Наименование КТ'].count()\
    .to_frame()\
    .reset_index()

ct_4852_count.columns = ['id', 'Кол-во КТ']

In [24]:
ct_4852_count

          id  Кол-во КТ
0     201471          4
1     201472          4
2     201485          5
3     201497          4
4     201501          6
...      ...        ...
1082  383396          5
1083  383397          4
1084  383398          4
1085  383399          4
1086  383489          7

[1087 rows x 2 columns]

In [25]:
er_fp.head(1)

,global_id,system_object_id,Наименование мероприятия (результата),Тип мероприятия (результата),Тип мероприятия (результата) (временно),Национальная цель,Показатель достижения цели,Национальный проект,Государственная программа,Федеральный проект,...,Структурный элемент (результат ФП или мероприятие ГП),Фактор,Подфактор,Комплекс мероприятий,Организация,Должность,ФИО,Наименование показателя мероприятия (результата),Ед. измерения,Ед. измерения (временно)
0,201471,8498468734,На базе образовательных организаций высшего об...,Меры господдержки (в т.ч. субсидии юридическим...,NaN,Возможности для самореализации и развития тала...,Вхождение РФ в число 10-ти ведущих стран мира ...,Образование,Развитие образования,Современная школа,...,Результат ФП,2.1.3 Кадровое обеспечение системы общего обра...,NaN,Обеспечение условий для профессионального разв...,Министерство просвещения Российской Федерации,Директор Департамента,Милехин Андрей Викторович,Количество созданных педагогических технопарк...,Единица,Единица

In [26]:
#Совмещение таблицы мероприятий с таблицей кол-ва КТ
ct_er_fp = er_fp.merge(ct_4852_count, how = 'left', left_on = 'global_id', right_on = 'id')

In [27]:
ct_er_fp.head(3)

,global_id,system_object_id,Наименование мероприятия (результата),Тип мероприятия (результата),Тип мероприятия (результата) (временно),Национальная цель,Показатель достижения цели,Национальный проект,Государственная программа,Федеральный проект,...,Подфактор,Комплекс мероприятий,Организация,Должность,ФИО,Наименование показателя мероприятия (результата),Ед. измерения,Ед. измерения (временно),id,Кол-во КТ
0,201471,8498468734,На базе образовательных организаций высшего об...,Меры господдержки (в т.ч. субсидии юридическим...,NaN,Возможности для самореализации и развития тала...,Вхождение РФ в число 10-ти ведущих стран мира ...,Образование,Развитие образования,Современная школа,...,NaN,Обеспечение условий для профессионального разв...,Министерство просвещения Российской Федерации,Директор Департамента,Милехин Андрей Викторович,Количество созданных педагогических технопарк...,Единица,Единица,201471.0,4.0
1,201472,8498454666,Педагогические работники и управленческие кадр...,Привлечение квалифицированных кадров,NaN,Возможности для самореализации и развития тала...,Вхождение РФ в число 10-ти ведущих стран мира ...,Образование,Развитие образования,Современная школа,...,NaN,Обеспечение условий для профессионального разв...,Министерство просвещения Российской Федерации,Директор Департамента,Милехин Андрей Викторович,Доля педагогических работников и управленчески...,Процент,Процент,201472.0,4.0
2,201485,8497485987,На базе общеобразовательных организаций создан...,"Приобретение товаров, работ, услуг","Приобретение товаров, работ, услуг",Возможности для самореализации и развития тала...,"Формирование эффективной системы выявления, по...",Образование,Развитие образования,Современная школа,...,NaN,"Создание новых мест, в том числе путем развити...",Министерство просвещения Российской Федерации,Директор Департамента,Руденок Мария Алексеевна,Количество созданных и функционирующирх на баз...,Единица,Единица,201485.0,5.0

In [28]:
ct_er_fp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 513 entries, 0 to 512
Data columns (total 27 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   global_id                                                               513 non-null    int64
 1   system_object_id                                                        463 non-null    object
 2   Наименование мероприятия (результата)                                   513 non-null    object
 3   Тип мероприятия (результата)                                            513 non-null    object
 4   Тип мероприятия (результата) (временно)                                 436 non-null    object
 5   Национальная цель                                                       513 non-null    object
 6   Показатель достижения цели                                              513 non-null    object
 7   Национальный проект                                                     513 non-null    object
 8   Государственная программа                                               472 non-null    object
 9   Федеральный проект                                                      513 non-null    object
 10  Основное мероприятие ГП                                                 0 non-null      object
 11  Заместители Председателя Правительства                                  503 non-null    object
 12  Документ-основание для реализации (реквизиты) (если не ГП и НП)         51 non-null     object
 13  Характеристика результата (ожидаемый результат реализации мероприятия)  513 non-null    object
 14  Код из Электронного бюджета                                             481 non-null    object
 15  Структурный элемент (результат ФП или мероприятие ГП)                   509 non-null    object
 16  Фактор                                                                  513 non-null    object
 17  Подфактор                                                               210 non-null    object
 18  Комплекс мероприятий                                                    513 non-null    object
 19  Организация                                                             513 non-null    object
 20  Должность                                                               513 non-null    object
 21  ФИО                                                                     513 non-null    object
 22  Наименование показателя мероприятия (результата)                        513 non-null    object
 23  Ед. измерения                                                           513 non-null    object
 24  Ед. измерения (временно)                                                455 non-null    object
 25  id                                                                      508 non-null    float64
 26  Кол-во КТ                                                               508 non-null    float64
dtypes: float64(2), int64(1), object(24)
memory usage: 112.2+ KB

In [29]:
#Оставление нужных столбцов в таблице
ct_er_short = ct_er_fp[['global_id', 
        'Наименование мероприятия (результата)',
        'Федеральный проект',
        'Код из Электронного бюджета',
         'id',
         'Кол-во КТ']]
ct_er_short

,global_id,Наименование мероприятия (результата),Федеральный проект,Код из Электронного бюджета,id,Кол-во КТ
0,201471,На базе образовательных организаций высшего об...,Современная школа,8498468734,201471.0,4.0
1,201472,Педагогические работники и управленческие кадр...,Современная школа,8498454666,201472.0,4.0
2,201485,На базе общеобразовательных организаций создан...,Современная школа,8497485987,201485.0,5.0
3,201497,Сформирована и функционирует единая федеральна...,Современная школа,8498443267,201497.0,4.0
4,201501,Проведено повышение квалификации штатных педаг...,Современная школа,8497503134,201501.0,6.0
...,...,...,...,...,...,...
508,247625,"АО ""Корпорация МСП"" совместно с иными институт...",Акселерация субъектов МСП,21968,247625.0,4.0
509,247627,Субъектам МСП обеспечен объем финансовой подде...,Акселерация субъектов МСП,8498312925,247627.0,3.0
510,247630,Субъектам МСП предоставлено имущество (в аренд...,Акселерация субъектов МСП,8498634064,247630.0,5.0
511,250736,Субъекты МСП обеспечены обучающими мероприятия...,Акселерация субъектов МСП,8498668170,250736.0,4.0
512,252241,Обеспечены льготные условия российским продавц...,Промышленный экспорт,8667262825,252241.0,8.0

In [30]:
#Суммарное кол-во КТ
ct_er_short['Кол-во КТ'].sum()

2838.0

In [31]:
#Загрузка выгрузки Минфина
mf_eb = pd.read_excel('ct_05102021_mf.xlsx')

In [32]:
mf_eb.head(3)

,#,"Тип (результат, КТ)",Идентификатор результата,Код Национального проекта,Наименование Национального проекта,Код Федерального проекта,Наименование Федерального проекта,Тип ОЗР/Задача,Идентификатор задачи ФП,Код Задачи Федерального проекта,...,Организация,Номер отчета,Год,Месяц,Идентификатор исполнения,Номер исполнения,Тип исполнения,Фактическая/прогнозная дата реализации,Статус из отчета,Комментарий
0,1,Промежуточный,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,A1.00-15-2021.08/0367,2021.0,8.0,8.680056e+09,NaN,Прогноз,2021-12-31,Отсутствие отклонений,В работе.Риски недостижения отсутствуют\nХод р...
1,2,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,3,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [33]:
mf_eb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31250 entries, 0 to 31249
Data columns (total 31 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   #                                         31250 non-null  int64
 1   Тип (результат, КТ)                       31250 non-null  object
 2   Идентификатор результата                  31250 non-null  int64
 3   Код Национального проекта                 31250 non-null  object
 4   Наименование Национального проекта        31250 non-null  object
 5   Код Федерального проекта                  31250 non-null  object
 6   Наименование Федерального проекта         31250 non-null  object
 7   Тип ОЗР/Задача                            27368 non-null  object
 8   Идентификатор задачи ФП                   27368 non-null  float64
 9   Код Задачи Федерального проекта           27368 non-null  float64
 10  Наименование Задачи Федерального проекта  27368 non-null  object
 11  Идентификатор Значения результата         31250 non-null  int64
 12  Код результата ФП                         31250 non-null  int64
 13  Наименование результата ФП                31250 non-null  object
 14  Идентификатор КТ                          25694 non-null  float64
 15  Способ создания                           25694 non-null  object
 16  Контрольная точка Федерального проекта    25694 non-null  object
 17  Плановый итоговый срок реализации         31250 non-null  datetime64[ns]
 18  Идентификатор ответственного исполнителя  31222 non-null  float64
 19  ФИО ответственного исполнителя            31222 non-null  object
 20  Должность                                 30998 non-null  object
 21  Организация                               31118 non-null  object
 22  Номер отчета                              11761 non-null  object
 23  Год                                       11761 non-null  float64
 24  Месяц                                     11761 non-null  float64
 25  Идентификатор исполнения                  11761 non-null  float64
 26  Номер исполнения                          9310 non-null   object
 27  Тип исполнения                            11761 non-null  object
 28  Фактическая/прогнозная дата реализации    11754 non-null  datetime64[ns]
 29  Статус из отчета                          11662 non-null  object
 30  Комментарий                               11755 non-null  object
dtypes: datetime64[ns](2), float64(7), int64(4), object(18)
memory usage: 7.4+ MB

In [34]:
#Фильтрация только КТ
mf_eb_ct = mf_eb[mf_eb['Тип (результат, КТ)'] == 'КТ'].copy()

In [35]:
mf_eb_ct.head(3)

,#,"Тип (результат, КТ)",Идентификатор результата,Код Национального проекта,Наименование Национального проекта,Код Федерального проекта,Наименование Федерального проекта,Тип ОЗР/Задача,Идентификатор задачи ФП,Код Задачи Федерального проекта,...,Организация,Номер отчета,Год,Месяц,Идентификатор исполнения,Номер исполнения,Тип исполнения,Фактическая/прогнозная дата реализации,Статус из отчета,Комментарий
1,2,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,3,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
3,4,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,A1.00-15-2021.03/0367-3,2021.0,3.0,8.596482e+09,A1.00-11-2021.03.10.14/0906,Факт,2021-03-03,Отсутствие отклонений,"Выполнено.\nПодтверждающие документы:\n1. ""Сог..."

In [36]:
mf_eb_ct.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25694 entries, 1 to 31249
Data columns (total 31 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   #                                         25694 non-null  int64
 1   Тип (результат, КТ)                       25694 non-null  object
 2   Идентификатор результата                  25694 non-null  int64
 3   Код Национального проекта                 25694 non-null  object
 4   Наименование Национального проекта        25694 non-null  object
 5   Код Федерального проекта                  25694 non-null  object
 6   Наименование Федерального проекта         25694 non-null  object
 7   Тип ОЗР/Задача                            22381 non-null  object
 8   Идентификатор задачи ФП                   22381 non-null  float64
 9   Код Задачи Федерального проекта           22381 non-null  float64
 10  Наименование Задачи Федерального проекта  22381 non-null  object
 11  Идентификатор Значения результата         25694 non-null  int64
 12  Код результата ФП                         25694 non-null  int64
 13  Наименование результата ФП                25694 non-null  object
 14  Идентификатор КТ                          25694 non-null  float64
 15  Способ создания                           25694 non-null  object
 16  Контрольная точка Федерального проекта    25694 non-null  object
 17  Плановый итоговый срок реализации         25694 non-null  datetime64[ns]
 18  Идентификатор ответственного исполнителя  25667 non-null  float64
 19  ФИО ответственного исполнителя            25667 non-null  object
 20  Должность                                 25486 non-null  object
 21  Организация                               25575 non-null  object
 22  Номер отчета                              9311 non-null   object
 23  Год                                       9311 non-null   float64
 24  Месяц                                     9311 non-null   float64
 25  Идентификатор исполнения                  9311 non-null   float64
 26  Номер исполнения                          9310 non-null   object
 27  Тип исполнения                            9311 non-null   object
 28  Фактическая/прогнозная дата реализации    9307 non-null   datetime64[ns]
 29  Статус из отчета                          9308 non-null   object
 30  Комментарий                               9305 non-null   object
dtypes: datetime64[ns](2), float64(7), int64(4), object(18)
memory usage: 6.3+ MB

In [37]:
print(mf_eb_ct['Идентификатор КТ'].count(), '- Всего')
print(mf_eb_ct['Идентификатор КТ'].nunique(), '- Уникальных')

25694 - Всего
25694 - Уникальных

In [38]:
#Сортировка с годом
mf_eb_ct['Ct_year'] = mf_eb_ct['Плановый итоговый срок реализации'].dt.year
mf_eb_ct_2021 = mf_eb_ct[mf_eb_ct['Ct_year'] == 2021].copy()

In [39]:
mf_result_ct = mf_eb_ct_2021.groupby('Идентификатор результата')['Тип (результат, КТ)'].count()\
    .to_frame()\
    .reset_index()
mf_result_ct.columns =['Идентификатор результата', 'Кол-во_КТ_ЭБ']
mf_result_ct

      Идентификатор результата  Кол-во_КТ_ЭБ
0                          305            15
1                          313             4
2                          340             5
3                          457            10
4                          458            11
...                        ...           ...
1152                8676519220             5
1153                8676522769             4
1154                8683465594             2
1155                8683466826             2
1156                8683671618             4

[1157 rows x 2 columns]

In [40]:
merged_er_mf_ct = ct_er_short\
    .merge(mf_result_ct, left_on = 'Код из Электронного бюджета', right_on = 'Идентификатор результата', how = 'left')
merged_er_mf_ct.head()

,global_id,Наименование мероприятия (результата),Федеральный проект,Код из Электронного бюджета,id,Кол-во КТ,Идентификатор результата,Кол-во_КТ_ЭБ
0,201471,На базе образовательных организаций высшего об...,Современная школа,8498468734,201471.0,4.0,8.498469e+09,6.0
1,201472,Педагогические работники и управленческие кадр...,Современная школа,8498454666,201472.0,4.0,8.498455e+09,12.0
2,201485,На базе общеобразовательных организаций создан...,Современная школа,8497485987,201485.0,5.0,8.497486e+09,10.0
3,201497,Сформирована и функционирует единая федеральна...,Современная школа,8498443267,201497.0,4.0,8.498443e+09,15.0
4,201501,Проведено повышение квалификации штатных педаг...,Современная школа,8497503134,201501.0,6.0,8.497503e+09,10.0

In [41]:
mf_eb.head(3)

,#,"Тип (результат, КТ)",Идентификатор результата,Код Национального проекта,Наименование Национального проекта,Код Федерального проекта,Наименование Федерального проекта,Тип ОЗР/Задача,Идентификатор задачи ФП,Код Задачи Федерального проекта,...,Организация,Номер отчета,Год,Месяц,Идентификатор исполнения,Номер исполнения,Тип исполнения,Фактическая/прогнозная дата реализации,Статус из отчета,Комментарий
0,1,Промежуточный,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,A1.00-15-2021.08/0367,2021.0,8.0,8.680056e+09,NaN,Прогноз,2021-12-31,Отсутствие отклонений,В работе.Риски недостижения отсутствуют\nХод р...
1,2,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,3,КТ,20922,A,"Национальный проект ""Культура""",A1,Обеспечение качественно нового уровня развития...,ОЗР,8.494194e+09,2.0,...,МИНИСТЕРСТВО КУЛЬТУРЫ РОССИЙСКОЙ ФЕДЕРАЦИИ,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [42]:
clean_res = merged_er_mf_ct.drop(['id', 'Идентификатор результата'], axis = 1)
clean_res.rename(columns={'Кол-во КТ':'Кол-во КТ_ЭР'}, inplace=True)
clean_res['Разница ЭР - ЭБ'] = clean_res['Кол-во КТ_ЭР'] - clean_res['Кол-во_КТ_ЭБ']
clean_res

,global_id,Наименование мероприятия (результата),Федеральный проект,Код из Электронного бюджета,Кол-во КТ_ЭР,Кол-во_КТ_ЭБ,Разница ЭР - ЭБ
0,201471,На базе образовательных организаций высшего об...,Современная школа,8498468734,4.0,6.0,-2.0
1,201472,Педагогические работники и управленческие кадр...,Современная школа,8498454666,4.0,12.0,-8.0
2,201485,На базе общеобразовательных организаций создан...,Современная школа,8497485987,5.0,10.0,-5.0
3,201497,Сформирована и функционирует единая федеральна...,Современная школа,8498443267,4.0,15.0,-11.0
4,201501,Проведено повышение квалификации штатных педаг...,Современная школа,8497503134,6.0,10.0,-4.0
...,...,...,...,...,...,...,...
508,247625,"АО ""Корпорация МСП"" совместно с иными институт...",Акселерация субъектов МСП,21968,4.0,3.0,1.0
509,247627,Субъектам МСП обеспечен объем финансовой подде...,Акселерация субъектов МСП,8498312925,3.0,3.0,0.0
510,247630,Субъектам МСП предоставлено имущество (в аренд...,Акселерация субъектов МСП,8498634064,5.0,5.0,0.0
511,250736,Субъекты МСП обеспечены обучающими мероприятия...,Акселерация субъектов МСП,8498668170,4.0,3.0,1.0
512,252241,Обеспечены льготные условия российским продавц...,Промышленный экспорт,8667262825,8.0,8.0,0.0

In [43]:
#output = clean_res[clean_res['Разница ЭР - ЭБ'] > 0]
#output

In [44]:
clean_res.to_excel('output_3.xlsx')